### ISSUE TITLE
Bookmarking is not working on on SCORM cloud, probably other LMS's

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt-contrib-bookmarking#15]
Bookmarking seems to be failing on this line:

https://github.com/adaptlearning/adapt-contrib-bookmarking/blob/master/js/adapt-contrib-bookmarking.js#L57

Error is 
TypeError: Cannot read property '_byAdaptID' of undefined(…)

this.locationID is null and not being set in checkRestoreLocation

**Comment by oliverfoster** [comment]
@dancgray did we solve this with the alternative branch merge? i'm sure you has said this was ok now..

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#867
