### ISSUE TITLE
Unusable on iPad in landscape

### ISSUE THREAD

**Issue by hbaileylxd** [adaptlearning/adapt-contrib-bookmarking#18]
On iPad in Landscape mode, Bookmarking banner goes off the bottom of the page and cannot be used unless turned to portait.

![photo](https://cloud.githubusercontent.com/assets/11558341/11238086/36a374e8-8ddb-11e5-9a00-f509a4ddf162.PNG)

**Comment by oliverfoster** [comment]
uhoh! that uses notify.... this is not good...

**Comment by oliverfoster** [comment]
can you list the iPad model and the iOS version?

**Comment by oliverfoster** [comment]
looks like it's in an iframe also

**Comment by hbaileylxd** [comment]
Mine is an iPad 2 on iOS9.1 although it happens on another iPad we have in the department.

It is running through Moodle in a popup window.

**Comment by oliverfoster** [comment]
thanks. does the navigation bar go off the top of the screen when you scroll?

**Comment by hbaileylxd** [comment]
Yes. Shouldn't it?!

PS you can't scroll the page you see above, it's immovable

**Comment by hbaileylxd** [comment]
The other iPad is :  16GB Wifi only iPad 4 
IOS version 7.0.6

**Comment by oliverfoster** [comment]
yea, it's in an iframe still :/ 

the fixed position things (the notify popups and navigation bar) should sit relative to the size of the browser window. 

when they're in an iframe this doesn't happen. the fixed position elements sit relative to the size of the iframe. the iframe height is determined by its content size and not by the size of the browser window (an horrific bug)... so if the iframe content (the adapt course page) is longer than the brower window, the popups will appear like they've done for you, in the middle of the iframe, not in the middle of the window.

you also can't scroll the content inside the iframe. so the navigation bar appears at the top of the iframe, but as you're scrolling the page which contains the iframe, the the content inside the iframe, the navigation bar scrolls off the screen.

you need to find a moodle setting which ditches the iframes... which is where my knowledge dies. perhaps someone else can help?

**Comment by oliverfoster** [comment]
~~https://docs.moodle.org/22/en/File_module_settings < suggests using "New Window" rather than "In Popup"~~ edit, wrong link: https://docs.moodle.org/22/en/SCORM_settings#Display_settings

**Comment by hbaileylxd** [comment]
Oh yes of course, the nav bar stays put when i preview in a browser. Hadn't noticed the switch!

Our Moodle course is in a new window.... we don't have a pop-up option. Plus we don't have the option to change how we show it as I'm not an administrator and any changes have to go through a lengthy change request process.

I am having to put some javascript in to my index.html already to force Moodle to get rid of some annoying css formats.

**Comment by hbaileylxd** [comment]
PS on PC from moodle in an iframe the bookmarking banner works fine, as does the nav bar.

**Comment by oliverfoster** [comment]
yea, all pc browsers appear to do iframes correctly. it's only ios which has issue.

**Comment by hbaileylxd** [comment]
ah ha. Yes just checked and our only options in Moodle are Current Window or New Window.

![image](https://cloud.githubusercontent.com/assets/11558341/11240211/cb5876e4-8de8-11e5-9163-8e3d3f429b3d.png)

**Comment by oliverfoster** [comment]
Pete (my boss) asks which version of Moodle you're using?

**Comment by hbaileylxd** [comment]
2.7 :)

**Comment by oliverfoster** [comment]
Two ticks, he's gone to ask the dudes from our LMS team.

**Comment by hbaileylxd** [comment]
heh - thanks Oli and Pete!

**Comment by oliverfoster** [comment]
i had the wrong help page btw > https://docs.moodle.org/22/en/SCORM_settings#Display_settings < says exactly what your screen shot does. Pete is gonna hop onto gitter and give you a response.

**Comment by hbaileylxd** [comment]
awesome

**Comment by kineopete** [comment]
Hi Helen, unfortunately both of those Moodle launch options use an iframe and so will cause these problems in iOS. There is a fix available in Totara (which is built on top of Moodle core code) which offers a third launch option - new window (simple) which doesn't use an iframe. 

These enhancements are often pushed back from Totara to Moodle, but we've just checked Moodle 2.8 and 2.9 and both versions have the same two launch options as 2.7. I will check-in with the Totara team to see if there have been any discussions with Moodle about the fix.

**Comment by hbaileylxd** [comment]
Fabulous. We are thinking of moving to Totara in a few years perhaps but doesn't help us now I guess.

Can I use css to modify the position of it to fixed for now?

**Comment by hbaileylxd** [comment]
Accordions and Assessment are also broken on iOS with Moodle.

**Comment by moloko** [comment]
hi @hmaffin why not launch in 'same window' then use the ['launch page' technique](https://community.adaptlearning.org/mod/forum/discuss.php?d=477#p2212) to have the course open itself in a new window?

**Comment by hbaileylxd** [comment]
Worth a shot I guess!

**Comment by oliverfoster** [comment]
Success?

**Comment by hbaileylxd** [comment]
OK well, almost. I used the launch.html and the following happens 
1. Navigation drawer and accordions work great now!
2. it never auto pops up my pop up window, I ALWAYS have to click on "click here to try again" even though my pop-up blocker is set to allow.
3. When I close the tab with the adapt course in it it sticks on the "Your course should load in a new window" screen (set in current window for Moodle) -this is more of an annoyance than a big problem but if you launch a SCORM course in a new window and then close that new window Moodle force returns to the course's main page.
4. Bookmarking banner is not showing up to ask me if I want to go back to my last visited page
_EDIT_ ah wait bookmarking is now showing up. I think this is linked to 3 above. If I use the "click here to try again" link after i close the course tab, rather than going back to the course's main page, it does not load bookmarking. If we could fix 3 this won't be a problem.

But ultimately yes so much better than it was before! Thanks so much Matt, Pete and Oli.

**Comment by oliverfoster** [comment]
https://github.com/oliverfoster/adapt-moodle could you give this extension a try? if you've got trickle there is a branch with a few fixes in to make it work located at https://github.com/adaptlearning/adapt-contrib-trickle/tree/feature/moodle-iframe

**Comment by moloko** [comment]
hi @hmaffin 
1. great stuff!
2. It does sound slightly like you might have another popup blocker in play... What browser are you using and does it make any difference if you use an alternative?
3. this is standard Moodle behaviour for any course that opens in same window, you have to click 'Exit Activity' (usually in the top right) or use the breadcrumb trail. Not quite sure why Moodle does this, possible something to do with supporting multi-SCO packages? I usually add something to launch.html to explain to the user that they need to click 'Exit Activity' once they have close the course.
4. Sorry I'm not sure why this would be, this should work fine. Bookmarking definitely configured correctly? If you switch on Moodle SCORM debugging (or the contrib-spoor debug window) can you see a bookmark being saved/retrieved? Does it work if you put the same course on another LMS like SCORM Cloud (minus the launch.html page)?

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#868
