### ISSUE TITLE
ChildView API neccessary?

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-bookmarking#57]
Do we need the extra `checkLocation` calls when a `view:childAdded` event is triggered? Wouldn't waiting for these to be scrolled into view be sufficient?

If keeping the ChildView API checks, we should maybe look to limit recalculation based on the added model type matching `this.bookmarkLevel`.

**Comment by oliverfoster** [comment]
Sounds good

**Comment by oliverfoster** [comment]
If the current window is larger than the first trickle, new content will be added but scroll won't occur. Keep existing behaviour.
